#:schema node_modules/wrangler/config-schema.json
name = "tattoo-template"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


######## PRODUCTION environment config ########

[[d1_databases]]
binding = "DB"
database_name = "tattoo-template-db"
database_id = "5c155747-06a6-495e-b3e4-3aaefe967fba"

[[r2_buckets]]
binding = "R2"
bucket_name = "tattoo-template-bucket-lf1rgcfdayj9wm2pz8fjn2ag"

[[services]]
binding = "CWBlurhash"
service = "blurhash-worker"

######## PRODUCTION environment config ########

[env.production.vars]
[[env.production.d1_databases]]
binding = "DB"
database_name = "tattoo-template-db"
database_id = "5c155747-06a6-495e-b3e4-3aaefe967fba"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "tattoo-template-bucket-lf1rgcfdayj9wm2pz8fjn2ag"

[[env.production.services]]
binding = "CWBlurhash"
service = "blurhash-worker"