CREATE TABLE `artist` (
	`artistId` integer PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`image` integer NOT NULL,
	`specialty` text,
	`block1ImageId` integer NOT NULL,
	`block1Description` text NOT NULL,
	`block2ImageId` integer NOT NULL,
	`block2Description` text NOT NULL,
	`imageFeed1ImageId` integer NOT NULL,
	`imageFeed2ImageId` integer NOT NULL,
	`imageFeed3ImageId` integer NOT NULL,
	`imageFeed4ImageId` integer NOT NULL,
	`imageFeed5ImageId` integer NOT NULL,
	`imageFeed6ImageId` integer NOT NULL,
	`imageFeed7ImageId` integer NOT NULL,
	`imageFeed8ImageId` integer NOT NULL,
	FOREIGN KEY (`image`) REFERENCES `image`(`imageId`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`block1ImageId`) REFERENCES `image`(`imageId`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`block2ImageId`) REFERENCES `image`(`imageId`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`imageFeed1ImageId`) REFERENCES `image`(`imageId`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`imageFeed2ImageId`) REFERENCES `image`(`imageId`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`imageFeed3ImageId`) REFERENCES `image`(`imageId`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`imageFeed4ImageId`) REFERENCES `image`(`imageId`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`imageFeed5ImageId`) REFERENCES `image`(`imageId`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`imageFeed6ImageId`) REFERENCES `image`(`imageId`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`imageFeed7ImageId`) REFERENCES `image`(`imageId`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`imageFeed8ImageId`) REFERENCES `image`(`imageId`) ON UPDATE no action ON DELETE cascade
);
